version: '3'
services:
  cozyformom-application:
    container_name: cozyformom-application
    image: anso33/cozy-for-mom
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - "8080"
    ports:
      - "8080:8080"
    volumes:
      - server-log:/celebee/log

volumes:
  server-log:
    external: true
