version: '3'
services:
  cozyformom-application:
    container_name: cozyformom-application
    image: anso33/cozy-for-mom
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - "8080"
    ports:
      - "8080:8080"
    logging:
      driver: "json-file"
      options:
        max-size: "10GB"
        max-file: "7"
        path: "/home/ubuntu/cozy-dev/log"
    restart: always

