name: Java CD with Gradle and Docker

on:
  push:
    branches: [ "main", "chore/cd-test" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: docker-compose.yml
        run: |
          touch docker-compose.yml
          echo "${{ secrets.DOCKER_COMPOSE }}" > docker-compose.yml
        shell: bash

      - name: make application-dev.yml
        run: |
          cd ./src/main/resources    
          echo "${{ secrets.DEV_YML }}" > application-dev.yml
        shell: bash
      #          echo "${{ secrets.DEV_YML }}" | base64 -d
      #        run: |
      #          touch ./src/main/resources/application-dev.yml
      #          echo $DEV_YML >> ./src/main/resources/application-dev.yml
      #          echo $DEV_YML
      #        shell: bash
      #        env:
      #          DEV_YML: ${{ secrets.DEV_YML }}

      # Github Repository Secrets를 통해 환경 변수 파일을 생성합니다.
      - name: Generate Environment Variables File for Production
        run: |
          echo "MYSQL_DATABASE_NAME=${{ secrets.MYSQL_DATABASE_NAME }}" >> .env
          echo "MYSQL_DATABASE_PASSWORD=${{ secrets.MYSQL_DATABASE_PASSWORD }}" >> .env
          echo "MYSQL_DATABASE_URL=${{ secrets.MYSQL_DATABASE_URL }}" >> .env
          echo "MYSQL_DATABASE_USERNAME=${{ secrets.MYSQL_DATABASE_USERNAME }}" >> .env

      - name: Set application.yml
        run: |
          sed -i "s|@MYSQL_DATABASE_NAME@|${{ secrets.MYSQL_DATABASE_NAME }}|g" ./src/main/resources/application-dev.yml
          sed -i "s|@MYSQL_DATABASE_PASSWORD@|${{ secrets.MYSQL_DATABASE_PASSWORD }}|g" ./src/main/resources/application-dev.yml
          sed -i "s|@MYSQL_DATABASE_URL@|${{ secrets.MYSQL_DATABASE_URL }}|g" ./src/main/resources/application-dev.yml
          sed -i "s|@MYSQL_DATABASE_USERNAME@|${{ secrets.MYSQL_DATABASE_USERNAME }}|g" ./src/main/resources/application-dev.yml

      - name: Grant execute permisson for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle (without Test)
        run: ./gradlew clean build -x test --stacktrace

      ## docker-compose 설치
      - name: Set up Docker-Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/1.28.5/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose


      - name: Docker Hub build & push
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker-compose build
          echo "df"
          docker images
          echo "hi"
          docker-compose push ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_REPO }}

      - name: Deploy to Prod WAS Server
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ${{ secrets.AWS_USER }}
          key: ${{ secrets.AWS_KEY }}
          port: ${{ secrets.AWS_PORT }}
          script: |
            cd /home/ubuntu/cozy-dev/
            sudo docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
            sudo docker-compose down
            sudo docker rm -f $(sudo docker ps -qa)
            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_REPO }}
            sudo docker-compose up -d
            sudo docker image prune -f

